spring:
  application.name: vegin
  profiles:
    default: local

---
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vegin?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/vegin?serverTimezone=UTC&characterEncoding=UTF-8
    username: vegin
    password: veginpass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    validate-on-migrate : false
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 20MB     # 파일 하나당 최대 20MB
      max-request-size: 20MB  # 요청 전체 최대 20MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
server:
  port: 8080

jwt:
  secret: 
  expiration: 3600000  # 1시간

cloud:
    s3:
      bucket: vegin-media-submit # <- s3보다 더 들여쓰기 (공백 2칸 또는 4칸)
      region: ap-northeast-2    # <- s3보다 더 들여쓰기
      cloudfront-url: https://dv8qbfh5v023k.cloudfront.net
    stack:
      auto: false

ai:
  fastapi:
    base-url: http://52.78.47.96:8000

app:
  frontend-url: https://dv8qbfh5v023k.cloudfront.net
